#ifndef __org_libreoffice_example_testc_idl__
#define __org_libreoffice_example_testc_idl__

#include <org/libreoffice/example/XTestc.idl>
module org { module libreoffice { module example { 	

	service Testc : org::libreoffice::example::XTestc {

	};

 }; }; };
#endif
