#ifndef __org_libreoffice_example_xcass_idl__
#define __org_libreoffice_example_xcass_idl__

module org { module libreoffice { module example { 	

	interface XCASS {
		[attribute] string wnKey;
		[attribute] string wnValue;
		sequence<string> getSynonym([in] string target);
	};

 }; }; };
#endif
