#ifndef __org_libreoffice_example_cass2_idl__
#define __org_libreoffice_example_cass2_idl__

#include <org/libreoffice/example/XCASS2.idl>
module org { module libreoffice { module example { 	

	service CASS2 : org::libreoffice::example::XCASS2 {

	};

 }; }; };
#endif
