#ifndef __com_chriswlucas_helloworld_helloworld_idl__
#define __com_chriswlucas_helloworld_helloworld_idl__

#include <com/chriswlucas/helloworld/XHelloworld.idl>
module com { module chriswlucas { module helloworld { 	

	service Helloworld : com::chriswlucas::helloworld::XHelloworld {

	};

 }; }; };
#endif
