#ifndef __com_chriswlucas_helloworld_xhelloworld_idl__
#define __com_chriswlucas_helloworld_xhelloworld_idl__

module com { module chriswlucas { module helloworld { 	

	interface XHelloworld {
		[attribute] string LadyName;
		string sayHello([in] boolean isBadBoy);

	};

 }; }; };
#endif
